### ISSUE TITLE
Example in README crashes

### ISSUE THREAD

**Issue by jrpool** [Siteimprove/alfa#1021]
The Usage section of the README file contains the example:

```javascript
import { Audit } from "@siteimprove/alfa-act";
import { Scraper } from "@siteimprove/alfa-scraper";

import rules from "@siteimprove/alfa-rules";

Scraper.with(async (scraper) => {
  for (const input of await scraper.scrape("http://example.com")) {
    const outcomes = await Audit.of(input, rules).evaluate();
  }
});
```

But this script executed with Node.js crashes on `Audit.of()` with the error message

```
TypeError: iterable is not iterable
    at Object.reduce (/Users/c162712/Documents/repos/autotest/node_modules/@siteimprove/alfa-iterable/src/iterable.js:70:29)
    at fromIterable (/Users/c162712/Documents/repos/autotest/node_modules/@siteimprove/alfa-list/src/list.js:467:41)
    at Function.from (/Users/c162712/Documents/repos/autotest/node_modules/@siteimprove/alfa-list/src/list.js:454:16)
    at Function.of (/Users/c162712/Documents/repos/autotest/node_modules/@siteimprove/alfa-act/src/audit.js:19:50)
    at file:///Users/c162712/Documents/repos/autotest/tests/alfastd.mjs:12:34
```

I believe this is because `rules` is not iterable.

**Comment by Jym77** [comment]
Hi @jrpool, thanks for reporting. I'll look into it. I guess we haven't updated the readme at some point.

In the meantime, please have a look at the [Alfa examples](https://github.com/Siteimprove/alfa-examples) repository where you'll hopefully find inspiration on using Alfa 😃

**Comment by Jym77** [comment]
Hi @jrpool I've tried the code with no problem on my side.
I do suspect things happening around JS/TS handling of modules (and import statements) which seems to be a complex topic to say the least 😓 

A possible issue is that this code is supposed to be TypeScript code that then needs to be built into JavaScript. When doing so (with a `tsconfig.json` similar to the main one in Alfa), I obtain the following JavaScript file:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const alfa_act_1 = require("@siteimprove/alfa-act");
const alfa_scraper_1 = require("@siteimprove/alfa-scraper");
const alfa_rules_1 = require("@siteimprove/alfa-rules");

alfa_scraper_1.Scraper.with(async (scraper) => {
    for (const input of await scraper.scrape("http://example.com")) {
        const outcomes = await alfa_act_1.Audit.of(input, alfa_rules_1.default).evaluate();
    }
});
```
which runs without problems (on Powershell on a windows box). 
Does this code work on your side? 


Another possible issue is Node version. Mine is v15.14.0. Our build scripts use Node v14 and 16, so I assume it should also work with these versions.

**Comment by jrpool** [comment]
Some analysis suggests that the error message had been due to using `rules` instead of `default` as the second argument to `Audit.of`.

The following code outputs an object representation of the page as `audit`.

But it outputs an empty object as `outcomes`.

```
const {Audit} = require('@siteimprove/alfa-act');
const {Scraper} = require('@siteimprove/alfa-scraper');
const alfaRules = require('@siteimprove/alfa-rules');
Scraper.with(async scraper => {
  for (const input of await scraper.scrape('https://example.com/')) {
    const audit = Audit.of(input, alfaRules.default);
    console.log(`audit is\n${JSON.stringify(audit, null, 2)}`);
    const outcomes = await audit.evaluate();
    console.log(JSON.stringify(`outcomes has type ${typeof outcomes}`));
    console.log(JSON.stringify(`outcomes is ${JSON.stringify(outcomes, null, 2)}`));
  }
});
```

**Comment by Jym77** [comment]
Can you try the full [scraping example](https://github.com/Siteimprove/alfa-examples/tree/main/custom-testing/scraping) (first run `yarn build` at top level of the examples repo, then run `yarn test` in the `custom-testing/scraping` directory).

It is essentially the same script as the one in the README.

---
When trying this version of your script:
```javascript
const { Audit } = require("@siteimprove/alfa-act");
const { Scraper } = require("@siteimprove/alfa-scraper");
const alfaRules = require("@siteimprove/alfa-rules");
Scraper.with(async (scraper) => {
  for (const input of await scraper.scrape("https://example.com/")) {
    const audit = Audit.of(input, alfaRules.default);

    const outcomes = await audit.evaluate();
    const result = [...outcomes];

    console.log(`Found ${result.length} outcomes`);
    console.log(result[0].toJSON());
  }
});
```
I get
```
Found 100 outcomes
{
  outcome: 'passed',
  rule: {
    type: 'atomic',
    uri: 'https://alfa.siteimprove.com/rules/sia-r1',
    requirements: [ [Object], [Object], [Object] ],
    tags: [ [Object] ]
  },
  target: {
    type: 'document',
    children: [ [Object], [Object] ],
    style: [ [Object] ]
  },
  expectations: [ [ '1', [Object] ], [ '2', [Object] ] ]
}
```
I think the difference comes from the fact that `outcomes` is just a generator and that is likely not properly stringified.
