### ISSUE TITLE
Import style rule can't be instantiated

### ISSUE THREAD

**Issue by singingknight** [Siteimprove/alfa#175]
When trying to instantiate a Style sheet containing an Import rule I get following error:

```
TypeError: Cannot set property rules of [object Object] which has only a getter
    at new Grouping (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule/grouping.js:7:20)
    at new Condition (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule/condition.js:6:9)
    at new Import (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule/import.js:9:9)
    at Function.of (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule/import.js:14:16)
    at Function.fromImport (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule/import.js:38:23)
    at Function.fromRule (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/rule.js:48:40)
    at /c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/sheet.js:32:56
    at Array.map (<anonymous>)
    at /c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/sheet.js:32:32
    at new Sheet (/c/siteimprove/dory/vendor/alfa/packages/alfa-dom/src/style/sheet.js:6:33)
```

The definition of `rules` as a property with only a getter in `packages/alfa-dom/src/style/rule/import.ts` conflicts with the super class `packages/alfa-dom/src/style/rule/grouping.ts` trying to set `rules` in the constructor

**Comment by kasperisager** [comment]
Gah, I hadn't actually expected this to manifest itself, but I shouldn't be surprised that it did 🙈 It's a wonderful bit of unsoundness that TypeScript allows and why I've been steadily moving classes to the private field/public getter pattern. That way, subclasses can safely override getters defined by superclasses without interfering with the backing fields. I should have started with the style rules apparently, but oh well 😄 Fix incoming!
