### ISSUE TITLE
Rule 17 audit - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rvantonisse** [Siteimprove/alfa#94]
Validating https://www.accessibility.nl/wai-tools/validation-test-sites/parkeertarieven-gemeente-amsterdam/ with all listed rules results in a RangeError with rule 17 (Maximum call stack size exceeded)

**Comment by rvantonisse** [comment]
Trace:
```
at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:14:33)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
  at isDisabled (/siteimprove-alfa/packages/alfa-dom/src/is-disabled.js:18:39)
```

**Comment by rvantonisse** [comment]
Runing only rule 17 is enough to trigger the reangeError

**Comment by kasperisager** [comment]
Thanks for the report! I think I know what the issue is 👍

**Comment by kasperisager** [comment]
Let me know if 14ae206 does the trick!

**Comment by rvantonisse** [comment]
Success! Trick done.
